### ISSUE TITLE
ExpressionDark theme support	

### ISSUE THREAD

**Issue by amerkoleci** [tgjones/gemini#111]
First of all, great project, it caught my attention when you posted about it on Perspex project.

Would be possible to add ExpressionDark theme?
I saw your adding VS 2013 theme support.

Keep your great work,

Thanks,

Amer

**Comment by amerkoleci** [comment]
Sorry to ping back here, are thoose themes integrated in current version? How do you apply Mah.Metro themes?

**Comment by tgjones** [comment]
Those themes are in the latest code here on GitHub, but I haven't released a version on NuGet with them. I hope to do that soon.

MahApps.Metro themes... Can you explain what you're trying to do? It should work now, although it might take some work to integrate them properly with Gemini's own themes.

I've been focusing on providing a really good set of default themes for Gemini, because I think that's what the majority of people will use.

**Comment by amerkoleci** [comment]
I was reading the http://mahapps.com/guides/quick-start.html, but didn't saw where you include Mah.MetroApps resources?

**Comment by tgjones** [comment]
I'm not sure that I'm using MahApps.Metro's styles anymore in Gemini's default themes. But you could certainly include them in your own project - just add them to your `App.xaml` as directed in that quickstart guide.

**Comment by amerkoleci** [comment]
Understand, so this means that the Buttons, CheckBox won't have the Metro, VS2013 look and feel right?

**Comment by tgjones** [comment]
Correct - you'd have to add those styles yourself. Hopefully it's pretty to do that in `App.xaml` - if you find that the styles aren't working as you expect, then please open a new issue and I'll take a look.
