### ISSUE TITLE
Same tool window appears multiple time on startup 

### ISSUE THREAD

**Issue by Nfactor26** [tgjones/gemini#148]
I created two classes that derives from Tool and additionally implements IToolBox interface with one method "LoadToolBoxItems" that i have created. In the module , i am using "IToolBox [] toolBoxes" in constructor which IOC container correctly resolves with two of my implementations of IToolBox. Now ,  i activate these tool windows A and B from menu. They become visible at bottom as expected. After restarting my application, i see two tool windows of type "A" always as my layout is saved wrongly with two instances of "A" instead of "A" and "B" . One of them is of the wrong type and crashes my window if i select it.

**Comment by EchterAgo** [comment]
I have this problem as well with getting multiple inspector windows to work simultaneously. This seems to be a bug in loading the state from ApplicationState.bin in LayoutItemStatePersister.LoadState. When there are multiple instances of the same type in the file it will only create one instance and then update the state of that one instance multiple times because it uses IoC.GetInstance. I think the correct approach would be to create a new instance for every persisted item in the file. I'm not sure yet how to do it properly, but I will post a patch if I find out.

**Comment by tgjones** [comment]
On your tool view model, can you try adding this attribute: 

``` csharp
[PartCreationPolicy(CreationPolicy.NonShared)]
public class MyToolViewModel : Tool
```

That will force MEF to create a new instance each time `IoC.GetInstance` is called.

Because `InspectorViewModel` (intentionally) doesn't have this attribute, you'll need to subclass it and add the attribute there. In theory, Gemini allows you to provide custom view models for built-in tools like that - see here for an example of overriding `ShellViewModel` with a custom class:

https://github.com/tgjones/gemini/blob/master/src/Gemini.Demo/Modules/Shell/ViewModels/ShellViewModel.cs#L15

I say "in theory", because I haven't tested it for `InspectorViewModel`.

**Comment by EchterAgo** [comment]
Oh, nice, thank you for the fast response. Tested it and it works. I also made some changes to the LayoutItemStatePersister to better handle corrupt state, basically create default documents and tools if there is a problem loading the persisted state. Will submit a patch soon.

**Comment by tgjones** [comment]
I don't think there's anything else left to do here? As mentioned above, if you want to have multiple instances of a tool window, do this:

``` csharp
[PartCreationPolicy(CreationPolicy.NonShared)]
public class MyToolViewModel : Tool
```
